### ISSUE TITLE
Missing documentation for Knowledge Graph feature

### ISSUE THREAD

**Issue by rampadc** [ibm-cloud-docs/discovery#239]
Click on the 'Learn more' link in Watson Discovery Knowledge Graph tab navigates to the following link which says "Page not found"

https://cloud.ibm.com/docs/services/discovery/building-kg.html

**Comment by NickyBleiel** [comment]
The Knowledge Graph Beta APIs are no longer accessible.  More information can be found here:

https://cloud.ibm.com/docs/services/discovery?topic=discovery-release-notes#3sept19
