### ISSUE TITLE
Link to Discovery docs doesn't show up anymore 

### ISSUE THREAD

**Issue by wksuser** [ibm-cloud-docs/discovery#242]
docs Discovery link [https://cloud.ibm.com/docs?tab=all-docs] goes to `Discovery-data` . https://cloud.ibm.com/docs/discovery-data?topic=discovery-data-getting-started#getting-started

<img width="1027" alt="image" src="https://user-images.githubusercontent.com/52053124/90537656-6e197d00-e132-11ea-97d6-0528764df355.png">

**Comment by NickyBleiel** [comment]
Thank you for the question. Correct, on this webpage you now are directed to the Discovery Cloud Pak for Data/Cloud Premium documentation set. However, you can still access the original Discovery Cloud docs at https://cloud.ibm.com/docs/discovery.
