### ISSUE TITLE
"On the Manage page, click Show Credentials." Unable to find it anywhere in my account on the IBM Cloud 

### ISSUE THREAD

**Issue by hicod** [ibm-cloud-docs/discovery#243]
Ref Document: https://cloud.ibm.com/docs/discovery?topic=discovery-gs-api
This web page document has the instructions to "Copy the credentials to authenticate to your service instance: "
          f. On the Manage page, click Show Credentials.
Clicking on "Manage" drops down a few options as follows:
    Enterprise
    Account
    Billing and usage
    Access (IAM)
    Catalog

Unable to find "Show Credentials" in any of these pages! Is the document wrong/insufficient or am I missing anything in following what document says?

**Comment by michelle-miller** [comment]
Ah, yes, you're right. There are two Manage menu items: one from the header menu and one in the navigation pane for the service overview page. To get the credentials at this point, follow these steps:

1. Log in to cloud.ibm.com. 
2. From the main menu, choose Resource list.
3. Expand the Services, and click to open the Discovery service instance you created.
4. On the service overview page, you will see a Credentials section. Click Show credentials from there. And you can copy the API key and URL values.

**Comment by hicod** [comment]
Thanks very much for a quick response. got what I was looking for 👍
