### ISSUE TITLE
Why does "AND" operator results differ when writing it in different style 

### ISSUE THREAD

**Issue by vivekatwal** [ibm-cloud-docs/discovery#245]
I am getting different results for 

```
text:Google,text:IBM
```

and 

```
text:Google,IBM
```

Reference
[AND operator](https://cloud.ibm.com/docs/discovery?topic=discovery-query-operators#and)

What is the difference between those queries ?

**Comment by michelle-miller** [comment]
Are you submitting these as a "query" (or as a "filter")? Is the difference you see in the number of returned documents or in the ranking of the documents?

**Comment by michelle-miller** [comment]
One this to mention is that the includes (`:`) operator gets precedence over the and (,) operator.
So, the different between those queries is that the second one is treated like this:

(text:Google) AND IBM

which will search for documents that mention "Google" in the `text` field and IBM in any field.

**Comment by michelle-miller** [comment]
Made updates to the documentation to hopefully better explain how the operators and their precedence works.
https://cloud.ibm.com/docs/discovery-data?topic=discovery-data-query-operators#and
